### ISSUE TITLE
React TODOs / upgrades

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-cards#31]
store.loading - allow for / display network & validation errors
deploy: minify images (at like 90% quality)
Re-add print button
Split off assets into separate repo. How to reference in themes? Likely need to update web pack... (perhaps make them globally accessible images rather than specific to a single theme, since they are shared anyway...)
Export options, such as backs or fronts only. Perhaps this should be a configuration panel?
  // i.e. web view vs page dimensions / cards per page, show fronts / backs / both, configurable padding around cards / card print size (though, how would that work with different-sized cards?)
  // Consider both in the context of different themes + different games, what will change / should be handled per-theme (aka CSS classes, such as card sizes...)
  // Perhaps move all of these filters and settings into a gear icon in top right w/ modal? But it's actually quite handy to have filters easily accessible, so maybe just render / export settings....
Templates... how can we streamline their creation?
  // Add example / starter template w/ readme
  // use https://github.com/milesj/interweave instead of dangerouslySetInnerHtml?

**Comment by smartin015** [comment]
Can these be separate bugs?

**Comment by toddmedema** [comment]
Done!
