### ISSUE TITLE
Split off assets into separate repo

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-cards#35]
How to reference in themes? Update icon helper + CSS.

Likely need to update web pack... (perhaps make them globally accessible images rather than specific to a single theme, since they are shared anyway...)

**Comment by smartin015** [comment]
We could have a "link" cell in the cards spreadsheet that references a compiled bundle checked into this new repo. That would entirely remove the need to reference specific repositories in the expedition-cards repo.

**Comment by toddmedema** [comment]
So the theme name would be coded into the spreadsheet rather than a changeable filter? Guess that makes sense for most use-cases, since most users won't be trying to render their cards for manufacturing...

Implementation-wise, could look like:
- webpack watches and re-renders themes into /dist/themes, and builds them there on deploys
- when it loads cards, it looks at the "Settings" table to get the theme name
- if you're dev'ing locally, it knows to pull from your local repo rather than prod so that you can dev on your theme

**Comment by smartin015** [comment]
That approach SGTM!
