### ISSUE TITLE
Promote to prod, CI and deployment scripts

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-cards#38]
Like every other Expedition repo, have a ./beta.sh that deploys to beta*.expedition, and ./prod.sh that deploys to *.expedition (and have CI deploy to beta on commit to master)

DONE: Before we can deploy to cards.expeditiongame.com, we need to create a page on the website listing the print and play PDFs and change the bit.ly link to point there instead, so that people aren't shoved into the card creator when they just want the PNP PDF
^^ which we'll want anyway, as we have more and more things available for PNP, such as different languages & expansions.
^^ This would also be a good place to incorporate buy links.

**Comment by toddmedema** [comment]
@smartin015 Added a hidden page to the website for PNP downloads: https://expeditiongame.com/cards
- let me know if that design looks good; if so, I'll migrate our email templates to link to that instead of directly to the PDF
- only concern I can think of is that since it's now just a page on the website, it'll be easier for people to share that link with friends / bypassing the signup link. But, since they have to use the app to play anyway (which has the announcements features, plus we ask if they want to sign up for the mailing list when they log in for search), I suspect that we'd still be able to connect with people who PNP and really enjoy the game.

Note that for the foreseeable future, we'll want to keep the cards pdf at cards.expeditiongame.com/cards.pdf so that people clicking on the bit.ly link (which is permanently embedded in both old Kickstarters) don't get broken links (apparently you have to pay for bitly enterprise to change link targets). Thinking that going forward, a good naming convention could be:

cards.pdf << base game, unchanged so that we don't break old links
cards-fr.pdf << with language code
cards-horror.pdf << with expansion name
cards-horror-fr.pdf << with expansion and language

**Comment by smartin015** [comment]
I'd recommend changing `Expedition PDFs` to `Expedition cards in PDF format`, since people want the cards, not a PDF :)

I'm not too concerned about direct sharing, due to the things you mentioned.

Naming convention SGTM.
