### ISSUE TITLE
Do you plan to translate to other languages?

### ISSUE THREAD

**Issue by dneise** [ExpeditionRPG/expedition-cards#40]
Hi, big fan of open source here. Do you plan to publish the cards in other langs as well? 

I'd be happy to translate to german.

**Comment by toddmedema** [comment]
Hey @dneise thank you for the kind offer! We have the offline rules translated her: https://github.com/ExpeditionRPG/expedition-app/blob/master/rules/German.md

Someone actually just finished the cards as well, but I haven't had a chance to adjust the card creator code to support it (primarily around moving the English strings hardcoded in the creator to a translations tab on the card sheet).

Unfortunately, we won't be able to support whole-app translation for a long time :(
