### ISSUE TITLE
PnP output: card backs should be right-aligned

### ISSUE THREAD

**Issue by golonko** [ExpeditionRPG/expedition-cards#44]
If I print the generated files as they are now and try to glue the sheet of backs to a sheet of fronts, the result will not be correct if there are cards requiring different backs in a single row.

Lets take as an example a sheet with identical 4 cards only. 3 cards in top row, 1 card in second row. 
If I glue the sheets together, the top row will work correctly, but the back of the card in second row will completely miss the front.

Can you make a fix to align the backs right-to-left and fronts left-to-right?
Otherwise, I have to cut all the cards before sticking the backs to fronts and that is far less than optimal :-)

**Comment by golonko** [comment]
maybe we could have an option for that? as honestly, i have no idea how to
print it as is.

**Comment by toddmedema** [comment]
It's meant to be printed double-sided on thicker paper, I've actually never heard of someone printing on two sheets and gluing them! Is that an option for you?

**Comment by golonko** [comment]
Well ok, "no idea" was a bit exaggerated on my part :)
Gluing two sheets together is quite common in the PnP society, where we
have to overcome home printer's really bad registration. I like to make my
cards as pro-looking as possible :)
When you glue two sheets, you can do all sorts of fun stuff like putting
black core in between.
But being a PnPer means overcoming different obstacles, so I'll figure
something out. Maybe it is just printer settings indeed :)

**Comment by toddmedema** [comment]
Oh neat! Well, give the printer settings a try and if that's still not working, let me know - shouldn't be too hard to rig up that setting.

Also, if you're willing to go a bit experimental, mind using our beta card creator? :) (that would also be where we first deploy any new settings) - http://betacards.expeditiongame.com

**Comment by golonko** [comment]
Yea, I'll try the beta tomorrow :)
While we're at it though... Where can I get access to the Google docs with the original card data? I'd like to try and start a Polish translation to play with my kids.

**Comment by toddmedema** [comment]
That would be great! Go ahead and email me at Todd@Fabricate.io and I'll share a copy of the sheet with you, along with instructions on how to translate it :)
